language: node_js
node_js: 6

dist: trusty

addons:
  chrome: stable

before_script:
  - npm install -g protractor
  - webdriver-manager update
  - npm run start-e2e
  - travis_wait 15

script:
  - npm test
