language: node_js
node_js: 6

dist: trusty

addons:
  chrome: stable

before_script:
  - npm install -g protractor
  - webdriver-manager update
  - travis_wait 1 npm run start-e2e

script:
  - npm test
